### PR TITLE
added target velocity functionality and tests

### PR DESCRIPTION
**Pull request by jacob-umich**
This will need to be merged at some point when full simulations are added, but I wanted to test out CI stuff on github.

### CODE REVIEW

**Comment by jacob-umich** [comment]
@AnvayPradhan @nzamb222 Can yall try to figure out why the automatic tests cant file the lapacke function? It worked last night but after I added the psuedo inverse function in the code, it won't work now.

**Comment by jacob-umich** [comment]
wiggly

**Comment by nzamb222** [comment]
is it the cube example or something else? Nice work

**Comment by jacob-umich** [comment]
@nzamb222 its supposed to just be simple fold but something has gone seriously wrong haha

**Comment by jacob-umich** [comment]
@nzamb222 If you get a chance, can you make sure I am making the projection matrix correctly in the simulation method of the structure class. it was really hard to make the animations and they do not look good. It could just be because the projection method isn't the best for specifying specific motions, but it could also be something is programmed wrong. I tried to write a test to verify that I was projecting correctly, but I could not get the test to pass.

**Review by nzamb222 — APPROVED** [review]

**Pull request merged**
